### ISSUE TITLE
Foundry 10 version not showing actor templates correctly

### ISSUE THREAD

**Issue by newbyr** [jsavko/vagabonds#11]
Loading the v10 update and checking, the actor templates now only show an item list.  No attributes or traits etc. seen

![image](https://user-images.githubusercontent.com/106149466/195992995-fee0da1e-c990-45ac-8c15-62d28c8f458a.png)
![image](https://user-images.githubusercontent.com/106149466/195993033-9defb53b-f499-474b-b3a5-c3eedede317e.png)

**Comment by jsavko** [comment]
Try giving it a control+f5 to clear the browser cache.  What version of foundry are you running?  Are you willing to send me a copy of your world folder?

**Comment by jsavko** [comment]
Was your issue resolved with 0.4.1?
