### ISSUE TITLE
No button on character sheet to directly add lineage or technique

### ISSUE THREAD

**Issue by DooNotResuscitate** [jsavko/vagabonds#4]
Both of these have to be searched for in the compendium and then dropped onto the character sheet.

**Comment by jsavko** [comment]
That is by design

**Comment by DooNotResuscitate** [comment]
> That is by design

If that is the case, could you mention that in the README? I almost create an issue that they couldn't be added at all.

**Comment by jsavko** [comment]
Fair enough

**Comment by jsavko** [comment]
You can also create a new technique or lineage from the items sidebar and add those to the sheet if you don't wish to use the ones in the compendium

**Comment by jsavko** [comment]
Updated the Readme to direct you to the compendiums for Lineage and Techniques
